# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main", "V5" ]
  pull_request:
    branches: [ "main", "V5" ]
  workflow_dispatch:
  
env:
  GO_VERSION: 1.21

jobs:
  ci:
    name: Vet, lint and test
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: ${{ env.GO_VERSION }}

    - name: Vet
      run: make vet

    # the official golanci-lint-action logs a lot of errors (https://github.com/golangci/golangci-lint-action/issues/135)
    # therefore it's replaced with a manual approach
    # - name: Lint
    #   uses: golangci/golangci-lint-action@v3

    - name: Lint
      run: |
        curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin
        golangci-lint run --out-format=github-actions

    - name: Test
      run: make test

    - name: Integration Test
      run: make test_integration
    
    - name: Reconnection Test
      run: make test_reconnection

  govulncheck:
    runs-on: ubuntu-latest
    name: Run govulncheck
    steps:
    - id: govulncheck
      uses: golang/govulncheck-action@v1
      with:
        go-version-input: ${{ env.GO_VERSION }}
        go-package: ./...
